// Generated by gencpp from file fulanghua_srvs/PoseResponse.msg
// DO NOT EDIT!


#ifndef FULANGHUA_SRVS_MESSAGE_POSERESPONSE_H
#define FULANGHUA_SRVS_MESSAGE_POSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fulanghua_srvs
{
template <class ContainerAllocator>
struct PoseResponse_
{
  typedef PoseResponse_<ContainerAllocator> Type;

  PoseResponse_()
    : status(false)  {
    }
  PoseResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::fulanghua_srvs::PoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fulanghua_srvs::PoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PoseResponse_

typedef ::fulanghua_srvs::PoseResponse_<std::allocator<void> > PoseResponse;

typedef boost::shared_ptr< ::fulanghua_srvs::PoseResponse > PoseResponsePtr;
typedef boost::shared_ptr< ::fulanghua_srvs::PoseResponse const> PoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fulanghua_srvs::PoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fulanghua_srvs::PoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fulanghua_srvs::PoseResponse_<ContainerAllocator1> & lhs, const ::fulanghua_srvs::PoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fulanghua_srvs::PoseResponse_<ContainerAllocator1> & lhs, const ::fulanghua_srvs::PoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fulanghua_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fulanghua_srvs::PoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fulanghua_srvs::PoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fulanghua_srvs::PoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fulanghua_srvs::PoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fulanghua_srvs::PoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fulanghua_srvs::PoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fulanghua_srvs::PoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::fulanghua_srvs::PoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::fulanghua_srvs::PoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fulanghua_srvs/PoseResponse";
  }

  static const char* value(const ::fulanghua_srvs::PoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fulanghua_srvs::PoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"\n"
;
  }

  static const char* value(const ::fulanghua_srvs::PoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fulanghua_srvs::PoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fulanghua_srvs::PoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fulanghua_srvs::PoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FULANGHUA_SRVS_MESSAGE_POSERESPONSE_H
