// Generated by gencpp from file mcl_3dl_msgs/LoadPCD.msg
// DO NOT EDIT!


#ifndef MCL_3DL_MSGS_MESSAGE_LOADPCD_H
#define MCL_3DL_MSGS_MESSAGE_LOADPCD_H

#include <ros/service_traits.h>


#include <mcl_3dl_msgs/LoadPCDRequest.h>
#include <mcl_3dl_msgs/LoadPCDResponse.h>


namespace mcl_3dl_msgs
{

struct LoadPCD
{

typedef LoadPCDRequest Request;
typedef LoadPCDResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadPCD
} // namespace mcl_3dl_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mcl_3dl_msgs::LoadPCD > {
  static const char* value()
  {
    return "b8646510804710605aeee202394f2fcf";
  }

  static const char* value(const ::mcl_3dl_msgs::LoadPCD&) { return value(); }
};

template<>
struct DataType< ::mcl_3dl_msgs::LoadPCD > {
  static const char* value()
  {
    return "mcl_3dl_msgs/LoadPCD";
  }

  static const char* value(const ::mcl_3dl_msgs::LoadPCD&) { return value(); }
};


// service_traits::MD5Sum< ::mcl_3dl_msgs::LoadPCDRequest> should match
// service_traits::MD5Sum< ::mcl_3dl_msgs::LoadPCD >
template<>
struct MD5Sum< ::mcl_3dl_msgs::LoadPCDRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mcl_3dl_msgs::LoadPCD >::value();
  }
  static const char* value(const ::mcl_3dl_msgs::LoadPCDRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mcl_3dl_msgs::LoadPCDRequest> should match
// service_traits::DataType< ::mcl_3dl_msgs::LoadPCD >
template<>
struct DataType< ::mcl_3dl_msgs::LoadPCDRequest>
{
  static const char* value()
  {
    return DataType< ::mcl_3dl_msgs::LoadPCD >::value();
  }
  static const char* value(const ::mcl_3dl_msgs::LoadPCDRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mcl_3dl_msgs::LoadPCDResponse> should match
// service_traits::MD5Sum< ::mcl_3dl_msgs::LoadPCD >
template<>
struct MD5Sum< ::mcl_3dl_msgs::LoadPCDResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mcl_3dl_msgs::LoadPCD >::value();
  }
  static const char* value(const ::mcl_3dl_msgs::LoadPCDResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mcl_3dl_msgs::LoadPCDResponse> should match
// service_traits::DataType< ::mcl_3dl_msgs::LoadPCD >
template<>
struct DataType< ::mcl_3dl_msgs::LoadPCDResponse>
{
  static const char* value()
  {
    return DataType< ::mcl_3dl_msgs::LoadPCD >::value();
  }
  static const char* value(const ::mcl_3dl_msgs::LoadPCDResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MCL_3DL_MSGS_MESSAGE_LOADPCD_H
