// Generated by gencpp from file mcl_3dl_msgs/LoadPCDResponse.msg
// DO NOT EDIT!


#ifndef MCL_3DL_MSGS_MESSAGE_LOADPCDRESPONSE_H
#define MCL_3DL_MSGS_MESSAGE_LOADPCDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mcl_3dl_msgs
{
template <class ContainerAllocator>
struct LoadPCDResponse_
{
  typedef LoadPCDResponse_<ContainerAllocator> Type;

  LoadPCDResponse_()
    : success(false)  {
    }
  LoadPCDResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LoadPCDResponse_

typedef ::mcl_3dl_msgs::LoadPCDResponse_<std::allocator<void> > LoadPCDResponse;

typedef boost::shared_ptr< ::mcl_3dl_msgs::LoadPCDResponse > LoadPCDResponsePtr;
typedef boost::shared_ptr< ::mcl_3dl_msgs::LoadPCDResponse const> LoadPCDResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator1> & lhs, const ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator1> & lhs, const ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mcl_3dl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcl_3dl_msgs/LoadPCDResponse";
  }

  static const char* value(const ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadPCDResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcl_3dl_msgs::LoadPCDResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCL_3DL_MSGS_MESSAGE_LOADPCDRESPONSE_H
