// Generated by gencpp from file mcl_3dl_msgs/LoadPCDRequest.msg
// DO NOT EDIT!


#ifndef MCL_3DL_MSGS_MESSAGE_LOADPCDREQUEST_H
#define MCL_3DL_MSGS_MESSAGE_LOADPCDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mcl_3dl_msgs
{
template <class ContainerAllocator>
struct LoadPCDRequest_
{
  typedef LoadPCDRequest_<ContainerAllocator> Type;

  LoadPCDRequest_()
    : pcd_path()  {
    }
  LoadPCDRequest_(const ContainerAllocator& _alloc)
    : pcd_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _pcd_path_type;
  _pcd_path_type pcd_path;





  typedef boost::shared_ptr< ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LoadPCDRequest_

typedef ::mcl_3dl_msgs::LoadPCDRequest_<std::allocator<void> > LoadPCDRequest;

typedef boost::shared_ptr< ::mcl_3dl_msgs::LoadPCDRequest > LoadPCDRequestPtr;
typedef boost::shared_ptr< ::mcl_3dl_msgs::LoadPCDRequest const> LoadPCDRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator1> & lhs, const ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pcd_path == rhs.pcd_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator1> & lhs, const ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mcl_3dl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89d85a975322d7866dba283fe6c40322";
  }

  static const char* value(const ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89d85a975322d786ULL;
  static const uint64_t static_value2 = 0x6dba283fe6c40322ULL;
};

template<class ContainerAllocator>
struct DataType< ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcl_3dl_msgs/LoadPCDRequest";
  }

  static const char* value(const ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string pcd_path\n"
;
  }

  static const char* value(const ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pcd_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadPCDRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcl_3dl_msgs::LoadPCDRequest_<ContainerAllocator>& v)
  {
    s << indent << "pcd_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.pcd_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCL_3DL_MSGS_MESSAGE_LOADPCDREQUEST_H
