// Generated by gencpp from file mcl_3dl_msgs/ResizeParticle.msg
// DO NOT EDIT!


#ifndef MCL_3DL_MSGS_MESSAGE_RESIZEPARTICLE_H
#define MCL_3DL_MSGS_MESSAGE_RESIZEPARTICLE_H

#include <ros/service_traits.h>


#include <mcl_3dl_msgs/ResizeParticleRequest.h>
#include <mcl_3dl_msgs/ResizeParticleResponse.h>


namespace mcl_3dl_msgs
{

struct ResizeParticle
{

typedef ResizeParticleRequest Request;
typedef ResizeParticleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResizeParticle
} // namespace mcl_3dl_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mcl_3dl_msgs::ResizeParticle > {
  static const char* value()
  {
    return "97da5de9999c5ce84f539773c8d0b2a3";
  }

  static const char* value(const ::mcl_3dl_msgs::ResizeParticle&) { return value(); }
};

template<>
struct DataType< ::mcl_3dl_msgs::ResizeParticle > {
  static const char* value()
  {
    return "mcl_3dl_msgs/ResizeParticle";
  }

  static const char* value(const ::mcl_3dl_msgs::ResizeParticle&) { return value(); }
};


// service_traits::MD5Sum< ::mcl_3dl_msgs::ResizeParticleRequest> should match
// service_traits::MD5Sum< ::mcl_3dl_msgs::ResizeParticle >
template<>
struct MD5Sum< ::mcl_3dl_msgs::ResizeParticleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mcl_3dl_msgs::ResizeParticle >::value();
  }
  static const char* value(const ::mcl_3dl_msgs::ResizeParticleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mcl_3dl_msgs::ResizeParticleRequest> should match
// service_traits::DataType< ::mcl_3dl_msgs::ResizeParticle >
template<>
struct DataType< ::mcl_3dl_msgs::ResizeParticleRequest>
{
  static const char* value()
  {
    return DataType< ::mcl_3dl_msgs::ResizeParticle >::value();
  }
  static const char* value(const ::mcl_3dl_msgs::ResizeParticleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mcl_3dl_msgs::ResizeParticleResponse> should match
// service_traits::MD5Sum< ::mcl_3dl_msgs::ResizeParticle >
template<>
struct MD5Sum< ::mcl_3dl_msgs::ResizeParticleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mcl_3dl_msgs::ResizeParticle >::value();
  }
  static const char* value(const ::mcl_3dl_msgs::ResizeParticleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mcl_3dl_msgs::ResizeParticleResponse> should match
// service_traits::DataType< ::mcl_3dl_msgs::ResizeParticle >
template<>
struct DataType< ::mcl_3dl_msgs::ResizeParticleResponse>
{
  static const char* value()
  {
    return DataType< ::mcl_3dl_msgs::ResizeParticle >::value();
  }
  static const char* value(const ::mcl_3dl_msgs::ResizeParticleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MCL_3DL_MSGS_MESSAGE_RESIZEPARTICLE_H
