// Generated by gencpp from file mcl_3dl_msgs/ResizeParticleResponse.msg
// DO NOT EDIT!


#ifndef MCL_3DL_MSGS_MESSAGE_RESIZEPARTICLERESPONSE_H
#define MCL_3DL_MSGS_MESSAGE_RESIZEPARTICLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mcl_3dl_msgs
{
template <class ContainerAllocator>
struct ResizeParticleResponse_
{
  typedef ResizeParticleResponse_<ContainerAllocator> Type;

  ResizeParticleResponse_()
    {
    }
  ResizeParticleResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResizeParticleResponse_

typedef ::mcl_3dl_msgs::ResizeParticleResponse_<std::allocator<void> > ResizeParticleResponse;

typedef boost::shared_ptr< ::mcl_3dl_msgs::ResizeParticleResponse > ResizeParticleResponsePtr;
typedef boost::shared_ptr< ::mcl_3dl_msgs::ResizeParticleResponse const> ResizeParticleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace mcl_3dl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcl_3dl_msgs/ResizeParticleResponse";
  }

  static const char* value(const ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResizeParticleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mcl_3dl_msgs::ResizeParticleResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MCL_3DL_MSGS_MESSAGE_RESIZEPARTICLERESPONSE_H
